### ISSUE TITLE
Need help in evaluating the difficulty of solving constraints

### ISSUE THREAD

**Issue by SOSCapture** [angr/simuvex#144]
I recently tried to add a feature in the angr that evaluates the difficulty of solving the constraints in each basic blocks. Weighting edges in CFG make CFG into a weighted value of the directed graph, and then use some shortest path algorithm to solve the source of the shortest path to the target node, to solve the optimal path. But I don't know how the constraint conditions in angr are expressed, is my idea feasible? I hope to get your help.

**Comment by ltfish** [comment]
You idea seems reasonable, but I'm not sure how feasible it is (I'm not an expert in this area).

Here are some resources that might be helpful to you:

- All constraints in angr are stored as claripy Boolean ASTs. The [Solver Engine page in angr-docs](https://docs.angr.io/docs/claripy.html) might be a good start.
- angr's CFG (both CFGFast and CFGAccurate) uses networkx.DiGraph to store the graph. You can definitely take the graph (by doing `cfg.graph`) and manually manipulate the nodes, adding labesl to edges, etc.
- [Director](https://github.com/angr/angr/blob/master/angr/exploration_techniques/director.py) implements a directed symbolic exploration strategy.

Let us know if you need more help.

**Comment by SOSCapture** [comment]
Thank you for your help. I will have a try.

**Comment by SOSCapture** [comment]
@ltfish  Hello Fish. Could you tell me how to associate the nodes with these constraints ? Are these constraints stored in each basic blocks?

**Comment by ltfish** [comment]
> Are these constraints stored in each basic blocks?

Constraints do not exist during fast CFG recovery. In angr, you can only get constraints from running a symbolic exploration (which is usually per-path), or from performing a forced execution (using CFGAccurate).

Constraints are not linked with basic blocks. Rather, constraints are linked to paths. From a high-level perspective, collecting all constraints (which are generated by evaluating each path predicate) along a path that leads to a certain basic block gives you constraints to that basic block with respect to **one** path. You may want to collect constraints from all possible paths leading to a basic block and union them to get "the constraints associated with that node". This is, however, not feasible in general (due to the huge number of paths in real-world cases).

A similar concept to what you are describing is called _weakest preconditions_. You probably want to read some related papers as a start.

**Comment by SOSCapture** [comment]
I got it ! thanks a lot .
